name: build

on:
  push:
    branches: [ main ]
# Could add PR builds for this later, not sure that we need it though.
  pull_request:
    branches: [ main ]

env:
  # Any necessary environment variables for the runner go here.
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3
      - name: 'Setup Java 17'
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 17
          cache: maven
      - name: 'Setup Gradle'
        uses: gradle/actions/setup-gradle@v3
      - name: 'Build with Gradle'
        run: ./gradlew bootjar
      # Publish the image as a downloadable artifact in the action run
      - name: upload archive
        uses: actions/upload-artifact@v3
        with:
            name: 'build_image'
            path: esep/outdoora
      # If we build out to a production environment, add the steps below here.